# Uncomment this line to define a global platform for your project
platform :ios, '16.0'
use_modular_headers!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  # Add environment variables dynamically to Generated.xcconfig
  generated_xcconfig_path = File.join(File.dirname(__FILE__), 'Flutter', 'Generated.xcconfig')
  File.open(generated_xcconfig_path, 'a') do |file|
    file.puts "GOOGLE_CLIENT_ID=211799055475-674p1ue4ar2to4j2e3i109cjm499j65g.apps.googleusercontent.com"
    file.puts "GOOGLE_CLIENT_ID_SCHEME=com.googleusercontent.apps.211799055475-674p1ue4ar2to4j2e3i109cjm499j65g"
  end
end
