// Mocks generated by Mockito 5.4.6 from annotations
// in snapchef/test/viewmodels/recipe_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:snapchef/services/recipe_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RecipeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeService extends _i1.Mock implements _i2.RecipeService {
  @override
  _i3.Future<Map<String, String>> generateRecipe(
          Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRecipe,
          [payload],
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<String> regenerateRecipeImage(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateRecipeImage,
          [payload],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #regenerateRecipeImage,
            [payload],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #regenerateRecipeImage,
            [payload],
          ),
        )),
      ) as _i3.Future<String>);
}
